# REVISION-PATCHED: fig02 panel (c) and fig05 panel (b) removed; see README.
#!/usr/bin/env python3
"""Regenerate all manuscript display figures from archived source data.

The script uses archived CSV/JSON source data for Figures 1-4 and the localization-ambiguity display. Figure 1a is regenerated by solving the documented passive lattice model.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

plt.rcParams.update({
    "font.size": 10.5,
    "axes.labelsize": 11,
    "axes.titlesize": 11,
    "legend.fontsize": 8.5,
    "xtick.labelsize": 9.5,
    "ytick.labelsize": 9.5,
    "lines.linewidth": 1.7,
    "lines.markersize": 5.5,
})

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
CODE = ROOT / "src"
sys.path.insert(0, str(CODE))

from lattice_baselines import PassiveCrackedStrip  # noqa: E402


def _panel_label(ax, label: str, x: float = 0.02, y: float = 0.96) -> None:
    ax.text(
        x,
        y,
        label,
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontweight="bold",
        fontsize=13,
        bbox=dict(facecolor="white", edgecolor="none", alpha=0.75, pad=1.5),
    )


def make_fig1(out: Path) -> None:
    cycle = pd.read_csv(DATA / "baseline_results" / "cycle_scan_ko.csv")

    strip = PassiveCrackedStrip(nx=64, ny=48, crack_half_length=8.0, k=1.0)
    result = strip.solve_initiation(delta_c=0.02)
    u_unit, _, _ = strip.solve(delta=1.0)
    deformed = strip.positions + 8.0 * result.initiation_displacement * u_unit

    fig, axs = plt.subplots(1, 2, figsize=(14.2, 5.2), gridspec_kw={"width_ratios": [1.05, 1.0]})
    ax = axs[0]
    for bid, bond in enumerate(strip.all_bonds):
        if bid in strip.removed_ids:
            continue
        p = deformed[bond.i]
        q = deformed[bond.j].copy()
        dx = q[0] - p[0]
        if dx > strip.period / 2:
            q[0] -= strip.period
        elif dx < -strip.period / 2:
            q[0] += strip.period
        if p[0] < -1 or p[0] > strip.period + 1 or q[0] < -1 or q[0] > strip.period + 1:
            continue
        ax.plot([p[0], q[0]], [p[1], q[1]], linewidth=0.34, alpha=0.52)
    for bid in strip.candidate_ids:
        bond = strip.all_bonds[bid]
        p = deformed[bond.i]
        q = deformed[bond.j].copy()
        dx = q[0] - p[0]
        if dx > strip.period / 2:
            q[0] -= strip.period
        elif dx < -strip.period / 2:
            q[0] += strip.period
        ax.plot([p[0], q[0]], [p[1], q[1]], linewidth=2.0)
    ax.set_aspect("equal")
    ax.set_xlim(0, strip.period)
    ax.set_xlabel("x")
    ax.set_ylabel("y (displacements magnified 8x)")
    ax.set_title("Passive pre-cracked triangular strip at initiation")
    # Local reference-configuration inset: the horizontal cleavage plane is
    # crossed by alternating / and \ bonds; horizontal bonds are parallel to it.
    iax = inset_axes(ax, width="38%", height="46%", loc="lower right", borderpad=1.0)
    right_id = max(strip.candidate_ids, key=lambda bid: strip.all_bonds[bid].midpoint_x or -1e9)
    tipx = float(strip.all_bonds[right_id].midpoint_x)
    tipy = float(0.5*(strip.positions[strip.all_bonds[right_id].i,1]+strip.positions[strip.all_bonds[right_id].j,1]))
    for bid, bond in enumerate(strip.all_bonds):
        p0 = strip.positions[bond.i].copy(); q0 = strip.positions[bond.j].copy()
        dx = q0[0]-p0[0]
        if dx > strip.period/2: q0[0] -= strip.period
        elif dx < -strip.period/2: q0[0] += strip.period
        mid = 0.5*(p0+q0)
        while mid[0]-tipx > strip.period/2: p0[0]-=strip.period; q0[0]-=strip.period; mid[0]-=strip.period
        while mid[0]-tipx < -strip.period/2: p0[0]+=strip.period; q0[0]+=strip.period; mid[0]+=strip.period
        if abs(mid[0]-tipx)>2.4 or abs(mid[1]-tipy)>1.8: continue
        if bid in strip.removed_ids:
            iax.plot([p0[0],q0[0]],[p0[1],q0[1]],'--',lw=1.4)
        elif bid in strip.candidate_ids:
            iax.plot([p0[0],q0[0]],[p0[1],q0[1]],lw=2.4)
        else:
            iax.plot([p0[0],q0[0]],[p0[1],q0[1]],lw=.7,alpha=.65)
    iax.axhline(tipy,ls=':',lw=.9)
    iax.text(tipx-1.35,tipy+.55,r'$\backslash$',fontsize=11)
    iax.text(tipx-.55,tipy+.55,'/',fontsize=11)
    iax.set_xlim(tipx-2.1,tipx+1.8); iax.set_ylim(tipy-1.45,tipy+1.45)
    iax.set_xticks([]); iax.set_yticks([]); iax.set_title("alternating crossing bonds",fontsize=8)
    _panel_label(ax, "(a)", x=-0.20, y=1.04)

    ax = axs[1]
    ax.plot(cycle["k_o"], cycle["work_total_density"], "o", label="finite bond sum")
    order = np.argsort(cycle["k_o"].to_numpy())
    ax.plot(cycle["k_o"].to_numpy()[order], cycle["analytic_density"].to_numpy()[order], "--", label="analytic")
    ax.set_xlabel(r"odd bond coefficient $k_o$")
    ax.set_ylabel(r"cycle work density $W_{\rm loop}/A$")
    ax.legend()
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)", x=-0.20, y=1.04)

    fig.tight_layout()
    fig.savefig(out / "fig01_model_cycle.pdf", bbox_inches="tight")
    plt.close(fig)


def make_fig2(out: Path) -> None:
    rad = pd.read_csv(DATA / "discrete_configurational_results" / "discrete_domain_radius_scan.csv")
    bal = pd.read_csv(DATA / "discrete_configurational_results" / "discrete_configurational_balance.csv")

    fig, axs = plt.subplots(1, 2, figsize=(9.8, 4.2))
    ax = axs[0]
    for ko in (0.0, 0.05, 0.10, 0.15, 0.20):
        d = rad[np.isclose(rad["k_o"], ko)].sort_values("R")
        ax.plot(d["R"], d["J_total"], "o-", label=fr"$k_o={ko:.2f}$")
    ax.set_xlabel(r"domain radius $R$")
    ax.set_ylabel(r"$J_h[q_R]$")
    ax.legend(fontsize=7.5)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(a)")

    ax = axs[1]
    odd = bal["direct_odd_term"].to_numpy()
    total = bal["excess_total"].to_numpy()
    full = odd + bal["active_change_even"].to_numpy()
    ax.plot(odd, total, "o", label="odd bond term")
    ax.plot(full, total, "s", label="odd + even redistribution")
    lim = 1.08 * max(np.max(np.abs(total)), np.max(np.abs(full)), np.max(np.abs(odd)))
    xx = np.linspace(-lim, lim, 200)
    ax.plot(xx, xx, "--", label="unit slope")
    ax.set_xlabel("discrete source contribution")
    ax.set_ylabel("active excess drift")
    ax.legend(fontsize=7.5)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)")

    fig.tight_layout()
    fig.savefig(out / "fig02_configurational_balance.pdf", bbox_inches="tight")
    plt.close(fig)

def make_fig3(out: Path) -> None:
    o = DATA / "protocol_family_results"
    u = pd.read_csv(o / "protocol_family_unit_scan.csv")
    t = pd.read_csv(o / "protocol_family_thresholds.csv")
    p = pd.read_csv(o / "representative_protocol_work_partition.csv")
    m = pd.read_csv(o / "same_endpoint_mobility_protocol_normalized.csv")
    state = pd.read_csv(DATA / "representation_symmetry_results" / "constructive_state_function_criterion.csv")

    fig, axs = plt.subplots(2, 2, figsize=(11.2, 8.0))
    ax = axs[0, 0]
    d = u[u.nx == 48].sort_values("k_o")
    load = 0.9
    s = d.fixed_remote_stress_unit.to_numpy()
    e = d.candidate_extension_unit.to_numpy()
    ad = d.fixed_protocol_work_unit.to_numpy()
    at = d.traction_protocol_work_unit.to_numpy()
    x = d.k_o.to_numpy()
    ax.plot(x, load**2 * s[0] ** 2 * ad / (s**2 * ad[0]), "o-", label="operational, fixed grip")
    ax.plot(x, load**2 * s[0] ** 2 * at / (s**2 * at[0]), "s-", label="operational, matched traction")
    ax.plot(state.k_o, state.state_function_measure, "D--", label=r"state part $-\Delta U_e$")
    ax.plot(x, load * s[0] * e / (s * e[0]), "^-", label="local tensile criterion")
    ax.axhline(1, ls="--", lw=1)
    ax.set_xlabel(r"$k_o/k$")
    ax.set_ylabel("normalized initiation measure")
    ax.legend(frameon=False, fontsize=7.3)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(a)")

    ax = axs[0, 1]
    for nx, mk in [(48, "o"), (64, "s")]:
        d = t[t.nx == nx].sort_values("load_fraction")
        ax.plot(d.load_fraction, d.fixed_grip_work_ratio_at_bond_threshold, mk + "-", label=f"fixed, Nx={nx}")
        ax.plot(d.load_fraction, d.matched_traction_work_ratio_at_bond_threshold, mk + "--", label=f"traction, Nx={nx}")
    ax.axhline(1, ls=":", lw=1)
    ax.set_xlabel(r"$P/P_{\rm init}^{\rm lat}$")
    ax.set_ylabel(r"$A^{\mathcal{P}}/G_c^{\mathcal{P}}$ at bond threshold")
    ax.legend(frameon=False, fontsize=7, ncol=2)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)", y=0.88)

    ax = axs[1, 0]
    labels = ["external", "odd", r"$-\Delta U_e$", "diss.", "cut", r"$A^{\mathcal{P}}$"]
    keys = ["external_work", "odd_work", "minus_even_energy_change", "viscous_dissipation", "cut_energy", "protocol_work"]
    xx = np.arange(len(labels))
    w = 0.36
    for name, off in [("fixed grip", -w / 2), ("matched traction", w / 2)]:
        r = p[p.protocol == name.replace(" ", "_")].iloc[0]
        ax.bar(xx + off, [r[k] for k in keys], w, label=name)
    ax.axhline(0, lw=0.8)
    ax.set_xticks(xx, labels, rotation=20)
    ax.set_ylabel("work per virtual advance")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(axis="y", alpha=0.25)
    _panel_label(ax, "(c)")

    ax = axs[1, 1]
    for ko, mk, label in [(0.0, "o", "passive"), (0.12, "s", r"$k_o=0.12$"), (0.222271, "^", r"$k_o=0.222$")]:
        d = m[np.isclose(m.k_o, ko)].sort_values("mobility_ratio")
        ax.plot(d.mobility_ratio, d.protocol_work_over_isotropic, mk + "-", label=label)
    ax.set_xscale("log", base=2)
    ax.set_xticks([0.5, 1, 2, 4], ["0.5", "1", "2", "4"])
    ax.axhline(1, ls=":", lw=1)
    ax.set_xlabel(r"mobility ratio $M_x/M_y$")
    ax.set_ylabel(r"$A^{\mathcal{P}_M}/A^{\mathcal{P}_{M=I}}$")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(d)", y=0.88)

    fig.tight_layout()
    fig.savefig(out / "fig04_protocol_family.pdf")
    plt.close(fig)


def make_fig4_bridge(out: Path) -> None:
    bridge = pd.read_csv(DATA / "configurational_work_bridge_results" / "J_work_matched_comparison.csv")
    soft = pd.read_csv(DATA / "configurational_work_bridge_results" / "two_parameter_quasistatic_softening.csv")
    fig, axs = plt.subplots(2, 2, figsize=(11.2, 8.2))

    ax = axs[0, 0]
    d = bridge[np.isclose(bridge.k_o, 0.0)].sort_values("a_lat_over_L")
    ax.plot(d.a_lat_over_L, d.J_h, "o-", label=r"$J_h$")
    ax.plot(d.a_lat_over_L, d.abrupt_work_over_advance, "s--", label=r"$A_{\rm tip}^{\mathcal{P}_D}/\Delta a$")
    ax.plot(d.a_lat_over_L, d.minus_delta_Ue_over_advance, "^:", label=r"$-\Delta U_e/\Delta a$")
    ax.set_xlabel(r"$a_{\rm lat}/L$")
    ax.set_ylabel("passive driving measure")
    ax.set_title(r"passive, $P/P_{\rm init}=0.90$")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=.25)
    _panel_label(ax,"(a)")

    ax = axs[0, 1]
    d = bridge[np.isclose(bridge.k_o, 0.2)].sort_values("a_lat_over_L")
    ax.plot(d.a_lat_over_L, d.J_h, "o-", label=r"$J_h$")
    ax.plot(d.a_lat_over_L, d.minus_delta_Ue_over_advance, "^:", label=r"$-\Delta U_e/\Delta a$")
    ax.plot(d.a_lat_over_L, d.abrupt_work_over_advance, "s--", label="abrupt work")
    ax.plot(d.a_lat_over_L, d.quasistatic_diagonal_work_over_advance, "D-.", label="quasistatic diagonal")
    ax.set_xlabel(r"$a_{\rm lat}/L$")
    ax.set_ylabel("active driving measure")
    ax.set_title(r"$k_o/k=0.20$, same lattice and remote load")
    ax.legend(frameon=False, fontsize=7.5)
    ax.grid(alpha=.25)
    _panel_label(ax,"(b)")

    ax = axs[1, 0]
    for ko, marker, label in [(0.0,"o-","passive"),(0.2,"s-",r"$k_o/k=0.20$")]:
        d=bridge[np.isclose(bridge.k_o,ko)].sort_values("a_lat_over_L")
        ax.plot(d.a_lat_over_L,100*np.abs(d.relative_J_vs_abrupt_difference),marker,label=label)
    ax.set_xlabel(r"$a_{\rm lat}/L$")
    ax.set_ylabel(r"$|J_h-A^{\mathcal{P}_D}/\Delta a|/|J_h|$ (\%)")
    ax.set_title("Rice--Eshelby equivalence gap")
    ax.legend(frameon=False,fontsize=8)
    ax.grid(alpha=.25)
    _panel_label(ax,"(c)")

    ax = axs[1, 1]
    order=["even_first","even_persists","diagonal","odd_persists","odd_first"]
    labels=["even\nfirst","even\npersists","diagonal","odd\npersists","odd\nfirst"]
    x=np.arange(len(order))
    for ko,marker in [(0.12,"o-"),(0.222271,"s-")]:
        d=soft[np.isclose(soft.k_o,ko)].set_index("path").loc[order]
        ax.plot(x,d.quasistatic_work_unit/d.quasistatic_work_unit.mean(),marker,label=fr"$k_o/k={ko:.3g}$")
    ax.set_xticks(x,labels)
    ax.set_ylabel(r"$A_{\rm tip}^{\mathrm{qs}}/\langle A_{\rm tip}^{\mathrm{qs}}\rangle$")
    ax.set_title("two-parameter debonding paths")
    ax.legend(frameon=False,fontsize=8)
    ax.grid(alpha=.25)
    _panel_label(ax,"(d)")

    fig.tight_layout()
    fig.savefig(out / "fig03_configurational_work_bridge.pdf", bbox_inches="tight")
    plt.close(fig)


def make_fig6_propagation(out: Path) -> None:
    steps = pd.read_csv(DATA / "advance_resistance_results" / "advance_scaled_steps.csv")
    periods = pd.read_csv(DATA / "advance_resistance_results" / "advance_period_summary.csv")
    cascades = pd.read_csv(DATA / "advance_resistance_results" / "cascade_robustness_scan.csv")
    positive = pd.read_csv(DATA / "advance_resistance_results" / "positive_control_scan.csv")

    nominal = steps[
        (steps.nx == 48)
        & np.isclose(steps.crack_fraction, 0.125)
        & np.isclose(steps.load_fraction, 0.90)
        & np.isclose(steps.k_o, 0.20)
    ].sort_values(["boundary_condition", "step"])
    comparison = pd.read_csv(DATA / "refinement_validation_results" / "passive_active_step_comparison.csv")

    fig, axs = plt.subplots(2, 2, figsize=(11.0, 8.2))
    ax = axs[0, 0]
    passive = comparison[np.isclose(comparison.k_o, 0.0)].sort_values("step")
    active = comparison[np.isclose(comparison.k_o, 0.2)].sort_values("step")
    ax.plot(passive.step, passive.extension_ratio, "o--", label=r"passive $\delta\ell_n/\delta_c$")
    ax.plot(active.step, active.extension_ratio, "s-", label=r"active $\delta\ell_n/\delta_c$")
    ax.plot(active.step, active.work_ratio, "^-", label=r"active $A_n^{\mathcal{P}}/R_n^{\rm eff}$")
    ax.axhline(1.0, linestyle=":", linewidth=1.0)
    ax.set_xticks([1, 2, 3, 4])
    ax.set_xlabel("successive crack-plane bond $n$")
    ax.set_ylabel("normalized step measure")
    ax.set_title(r"Fixed grip: $P/P_{\rm init}=0.90$")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(a)")

    ax = axs[0, 1]
    for bc, marker, label in [
        ("fixed_grip", "o-", "fixed grip"),
        ("dead_load", "s--", "constant traction"),
    ]:
        d = nominal[nominal.boundary_condition == bc]
        ax.plot(d.step, d.odd_work / d.effective_resistance, marker, label=label)
    ax.axhline(0.0, linestyle=":", linewidth=1.0)
    ax.set_xticks([1, 2, 3, 4])
    ax.set_xlabel("successive crack-plane bond $n$")
    ax.set_ylabel(r"$W_{\mathrm{odd},n}/R_n^{\mathrm{eff}}$")
    ax.set_title("Odd work alternates over two lattice periods")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)")

    ax = axs[1, 0]
    d = periods[
        np.isclose(periods.crack_fraction, 0.125)
        & np.isclose(periods.load_fraction, 0.90)
        & np.isclose(periods.k_o, 0.20)
    ].copy()
    d["a_over_L"] = 1.0 / d.nx
    for bc, period, marker, label in [
        ("fixed_grip", 1, "o-", "fixed, period 1"),
        ("fixed_grip", 2, "s-", "fixed, period 2"),
        ("dead_load", 1, "o--", "traction, period 1"),
        ("dead_load", 2, "s--", "traction, period 2"),
    ]:
        q = d[(d.boundary_condition == bc) & (d.period == period)].sort_values("a_over_L")
        ax.plot(q.a_over_L, q.work_ratio, marker, label=label)
    ax.axhline(1.0, linestyle=":", linewidth=1.0)
    ax.axvline(1.0 / 32.0, linestyle=":", linewidth=0.8)
    ax.text(1.0 / 32.0, ax.get_ylim()[0] + 0.02 * (ax.get_ylim()[1] - ax.get_ylim()[0]),
            r"$a_0=4a_{\rm lat}$", rotation=90, va="bottom", ha="right", fontsize=7)
    ax.set_xlabel(r"lattice spacing ratio $a_{\rm lat}/L$")
    ax.set_ylabel(r"$(A_{2m-1}+A_{2m})/(R_{2m-1}+R_{2m})$")
    ax.set_title(r"Cleavage-period balance at $P/P_{\mathrm{init}}=0.90$")
    ax.legend(frameon=False, fontsize=7, ncol=2)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(c)")

    ax = axs[1, 1]
    unrestricted = pd.read_csv(DATA / "configurational_work_bridge_results" / "unrestricted_all_bond_cascades.csv")
    p_values = sorted(unrestricted.load_fraction.unique())
    base = unrestricted[(unrestricted.nx == 48) & np.isclose(unrestricted.crack_fraction, 0.125)
                        & (unrestricted.boundary_condition == "dead_load")]
    for ko, marker in [(0.0, "o-"), (0.12, "s--"), (0.20, "^-."), (0.30, "d:")]:
        d = base[np.isclose(base.k_o, ko)]
        if d.empty:
            continue
        ax.plot(p_values,
                [int(d[np.isclose(d.load_fraction, p)].broken_bonds.iloc[0]) for p in p_values],
                marker, label=fr"$k_o/k={ko:g}$")
    cutoff = int(unrestricted.broken_bonds.max())
    ax.axhline(cutoff, ls=":", lw=1, color="0.4")
    ax.set_xlabel(r"initial load $P/P_{\mathrm{init}}$")
    ax.set_ylabel("all-bond deletions")
    ax.set_title("Activity lowers the cascade threshold")
    ax.text(0.03, 0.94,
            f"$48\\times36$, $a_0/L=0.125$, constant traction\n92/224 states reach the {cutoff}-deletion cutoff",
            transform=ax.transAxes, va="top", fontsize=7,
            bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "alpha": 0.8, "linewidth": 0.6})
    ax.legend(frameon=False, fontsize=7.5, loc="center right")
    ax.grid(alpha=.25)
    _panel_label(ax, "(d)")

    fig.tight_layout()
    fig.savefig(out / "fig06_propagation_and_branching.pdf", bbox_inches="tight")
    plt.close(fig)

def make_extended_data_fig1(out: Path) -> None:
    df = pd.read_csv(DATA / "localization_gauge_results" / "triangle_partition_gauge.csv")
    fig, axs = plt.subplots(1, 3, figsize=(12.8, 3.7))
    ax = axs[0]
    ax.plot(df.alpha_upper, df.active_excess_total, "o-", label=r"$\Delta J_h$")
    ax.plot(df.alpha_upper, df.active_excess_odd, "s-", label=r"$J_h^o$")
    ax.plot(df.alpha_upper, df.active_excess_even, "^-", label=r"$\Delta J_h^e$")
    ax.axhline(0, ls="--", lw=1)
    ax.axvline(0.5, ls=":", lw=1)
    ax.set_xlabel(r"upper-triangle share $\alpha$")
    ax.set_ylabel("annular active excess")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(a)")

    ax = axs[1]
    ax.plot(df.alpha_upper, 100 * df.passive_shell / df.passive_J4, "o-")
    ax.axhline(0, ls="--", lw=1)
    ax.axvline(0.5, ls=":", lw=1)
    ax.set_xlabel(r"upper-triangle share $\alpha$")
    ax.set_ylabel(r"passive shell drift / $J_h(R_i)$ (%)")
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)")

    ax = axs[2]
    ax.semilogy(df.alpha_upper, df.force_repro_active, "o-", label="active")
    ax.semilogy(df.alpha_upper, df.force_repro_passive, "s-", label="passive")
    ax.axvline(0.5, ls=":", lw=1)
    ax.set_xlabel(r"upper-triangle share $\alpha$")
    ax.set_ylabel("nodal-force reconstruction error")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(c)")

    fig.tight_layout()
    fig.savefig(out / "figA1_localization_ambiguity.pdf", bbox_inches="tight")
    plt.close(fig)



def make_fig5_scaling(out: Path) -> None:
    gauge = pd.read_csv(DATA / "gauge_convergence_results" / "gauge_convergence_summary.csv")
    fits = pd.read_csv(DATA / "gauge_convergence_results" / "gauge_convergence_fits.csv")
    size = pd.read_csv(DATA / "same_endpoint_size_scaling_results" / "size_normalized_summary.csv")
    four_size = DATA / "continuum_lattice_validation_results" / "path_coefficient_four_size.csv"
    if four_size.exists():
        size = pd.read_csv(four_size)
    finite = pd.read_csv(DATA / "same_endpoint_size_scaling_results" / "finite_ko_pair_differences.csv")

    fig, axs = plt.subplots(1, 3, figsize=(10.8, 3.7))

    ax = axs[0]
    for R_over_L, marker in [(0.075, "o"), (0.10, "s"), (0.125, "^")]:
        d = gauge[np.isclose(gauge.k_o, 0.15) & np.isclose(gauge.R_over_L, R_over_L)].sort_values("a_lat_over_L")
        ax.loglog(d.a_lat_over_L, d.active_relative_gauge_span, marker + "-", label=fr"$R/L={R_over_L:.3f}$")
        f = fits[np.isclose(fits.k_o, 0.15) & np.isclose(fits.R_over_L, R_over_L)].iloc[0]
        xx = np.linspace(d.a_lat_over_L.min(), d.a_lat_over_L.max(), 100)
        ax.loglog(xx, f.active_relative_prefactor * xx ** f.active_relative_exponent, "--", linewidth=1)
    ax.set_xlabel(r"lattice spacing ratio $a_{\rm lat}/L$")
    ax.set_ylabel(r"relative partition span")
    ax.legend(frameon=False)
    ax.grid(alpha=0.25, which="both")
    _panel_label(ax, "(a)")

    ax = axs[1]
    d = size.sort_values("a_lat_over_L")
    ax.plot(d.a_lat_over_L, d.phi_span_over_passive_resistance, "o", label="finite lattices")
    coeff = np.polyfit(d.a_lat_over_L, d.phi_span_over_passive_resistance, 1)
    xx = np.linspace(0.0, 1.05 * d.a_lat_over_L.max(), 100)
    ax.plot(xx, np.polyval(coeff, xx), "--", label=r"linear in $a_{\rm lat}/L$")
    ax.plot([0.0], [np.polyval(coeff, 0.0)], "s", label="intercept")
    ax.set_xlabel(r"$a_{\rm lat}/L$")
    ax.set_ylabel(r"$[\max\Phi-\min\Phi]/R_{\rm pass}$")
    ax.legend(frameon=False)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)")

    ax = axs[2]
    for nx, marker in [(32, "o"), (48, "s"), (64, "^")]:
        d = finite[finite.nx == nx].sort_values("prediction_over_passive_resistance")
        ax.plot(d.prediction_over_passive_resistance, d.actual_over_passive_resistance, marker, label=fr"$N_x={nx}$")
    lim = 1.08 * max(np.max(np.abs(finite.prediction_over_passive_resistance)), np.max(np.abs(finite.actual_over_passive_resistance)))
    xx = np.linspace(-lim, lim, 200)
    ax.plot(xx, xx, "--", linewidth=1, label="first-order equality")
    ax.set_xlabel(r"$k_o\Delta\Phi/R_{\rm pass}$")
    ax.set_ylabel(r"measured $\Delta A/R_{\rm pass}$")
    ax.legend(frameon=False)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(c)")

    fig.tight_layout()
    fig.savefig(out / "fig05_refinement_scaling.pdf", bbox_inches="tight")
    plt.close(fig)


def make_fig7(out: Path) -> None:
    summary = pd.read_csv(DATA / "directional_driving_results" / "directional_case_summary.csv")
    work = pd.read_csv(DATA / "directional_driving_results" / "directional_protocol_work.csv")
    force = pd.read_csv(DATA / "directional_driving_results" / "directional_configurational_force.csv")

    fig, axs = plt.subplots(2, 2, figsize=(11.0, 8.2))

    ax = axs[0, 0]
    for angle, marker in [(-60, "o"), (0, "s"), (60, "^")]:
        radians = np.deg2rad(angle)
        endpoint = np.array([np.cos(radians), np.sin(radians)])
        ax.annotate("", xy=endpoint, xytext=(0, 0), arrowprops=dict(arrowstyle="->", linewidth=1.8))
        ax.plot(endpoint[0], endpoint[1], marker)
        ax.text(1.08 * endpoint[0], 1.08 * endpoint[1], fr"${angle}^\circ$", ha="center", va="center")
    ax.plot(0, 0, "ko", markersize=4)
    ax.set_aspect("equal")
    ax.set_xlim(-0.05, 1.2)
    ax.set_ylim(-1.05, 1.05)
    ax.set_xlabel(r"local crack-advance direction $X_1$")
    ax.set_ylabel(r"$X_2$")
    ax.set_title("Equal-length two-edge dual paths")
    ax.grid(alpha=0.25)
    _panel_label(ax, "(a)")

    ax = axs[0, 1]
    d = work[(work.nx == 48) & (work.tip == "right")].copy()
    passive_straight = float(d[(np.isclose(d.k_o, 0.0)) & (d.direction_deg == 0)].protocol_work_unit.iloc[0])
    for ko, marker in [(-0.2, "o-"), (0.0, "s--"), (0.2, "^-")]:
        q = d[np.isclose(d.k_o, ko)].sort_values("direction_deg")
        ax.plot(q.direction_deg, q.protocol_work_unit / passive_straight, marker, label=fr"$k_o/k={ko:+.1f}$")
    ax.set_xticks([-60, 0, 60], [r"$-60^\circ$", r"$0^\circ$", r"$+60^\circ$"])
    ax.set_xlabel("virtual extension direction")
    ax.set_ylabel(r"$A^{\mathcal{P}}(\varphi)/A_0^{\mathcal{P}}(0)$")
    ax.set_title(r"$48\times36$ right tip")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(b)")

    ax = axs[1, 0]
    for ko, marker in [(-0.2, "o-"), (0.2, "s-")]:
        q = summary[(summary.tip == "right") & np.isclose(summary.k_o, ko)].sort_values("a_lat_over_L")
        ax.plot(q.a_lat_over_L, q.odd_excess_kink_work_bias_over_passive_straight, marker, label=fr"$k_o/k={ko:+.1f}$")
    ax.axhline(0.0, linestyle=":", linewidth=1.0)
    ax.set_xlabel(r"lattice spacing ratio $a_{\rm lat}/L$")
    ax.set_ylabel(r"$\{[A_+-A_-]_{k_o}-[A_+-A_-]_0\}/A_0(0)$")
    ax.set_title("Odd-induced directional excess")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(c)")

    ax = axs[1, 1]
    q = force[(force.nx == 48) & (force.tip == "right") & np.isclose(force.R_over_L, 0.10)]
    passive_x = float(q[(np.isclose(q.k_o, 0.0)) & (q.direction_deg == 0) & np.isclose(q.alpha_upper, 0.5)].J_total_x.iloc[0])
    for ko, marker in [(-0.2, "o-"), (0.2, "s-")]:
        vals = []
        alphas = []
        for alpha in sorted(q.alpha_upper.unique()):
            z = q[np.isclose(q.k_o, ko) & np.isclose(q.alpha_upper, alpha)]
            plus = float(z[z.direction_deg == 60].odd_excess_J_projection.iloc[0])
            minus = float(z[z.direction_deg == -60].odd_excess_J_projection.iloc[0])
            alphas.append(alpha)
            vals.append((plus - minus) / passive_x)
        ax.plot(alphas, vals, marker, label=fr"$k_o/k={ko:+.1f}$")
    ax.axhline(0.0, linestyle=":", linewidth=1.0)
    ax.set_xlabel(r"upper-triangle localization share $\alpha$")
    ax.set_ylabel(r"odd-excess $[J(+60^\circ)-J(-60^\circ)]/J_x^0$")
    ax.set_title(r"Configurational sign is partition-robust, $R/L=0.10$")
    ax.legend(frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    _panel_label(ax, "(d)")

    fig.tight_layout()
    fig.savefig(out / "fig07_directional_driving.pdf", bbox_inches="tight")
    plt.close(fig)

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "manuscript" / "figures")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    for old in args.out.glob("*.pdf"):
        old.unlink()
    make_fig1(args.out)
    make_fig2(args.out)
    make_fig3(args.out)
    make_fig4_bridge(args.out)
    make_fig5_scaling(args.out)
    make_fig6_propagation(args.out)
    make_fig7(args.out)
    make_extended_data_fig1(args.out)
    print(f"Generated seven main PDF figures and one appendix figure in {args.out}")


if __name__ == "__main__":
    main()
