#!/usr/bin/env python3
"""Fit lattice crack-tip stresses to the continuum odd-elastic Williams basis.

The fit uses the local quadratic reconstruction already employed by the
configurational-domain calculation.  In a tip-local annulus, the reconstructed
stress is represented by

    sigma = r^-1/2 (K_I Sigma_I^(1/2) + K_II Sigma_II^(1/2))
          + r^+1/2 (C_I Sigma_I^(3/2) + C_II Sigma_II^(3/2))
          + sigma_background.

The leading and next Williams sectors are generated by the continuum solver in
``crack_tip_asymptotics.py`` with the exact homogenized moduli of the lattice.
An otherwise identical passive-basis fit quantifies whether the odd angular
functions carry information beyond generic background terms.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import csv
import json
import math
import sys
from typing import Iterable

import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from active_tip_scan import ActiveCrackedStrip
from apparent_j_analysis import LocalTipField
from crack_tip_asymptotics import OddModuli, sample_K_field

Array = np.ndarray
SQRT3 = math.sqrt(3.0)
COMPONENTS = ((0, 0), (0, 1), (1, 0), (1, 1))


@dataclass(frozen=True)
class LatticeStressSamples:
    radius: Array
    theta: Array
    stress: Array


def homogenized_moduli(k: float, k_o_local: float) -> OddModuli:
    return OddModuli(
        B=SQRT3 * k / 2.0,
        mu=SQRT3 * k / 4.0,
        A_o=-SQRT3 * k_o_local / 2.0,
        K_o=-SQRT3 * k_o_local / 4.0,
    )


def write_csv(path: Path, rows: Iterable[dict[str, object]]) -> None:
    rows = list(rows)
    if not rows:
        raise ValueError(f"No rows supplied for {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def sample_lattice_stress(
    model: ActiveCrackedStrip,
    displacement: Array,
    tip: str,
    radii: Array,
    angles: Array,
    fit_radius: float,
) -> tuple[LocalTipField, LatticeStressSamples]:
    field = LocalTipField(model, displacement, tip=tip, fit_radius=fit_radius)
    radius_values: list[float] = []
    angle_values: list[float] = []
    stress_values: list[Array] = []
    for radius in radii:
        for angle in angles:
            x = float(radius * math.cos(float(angle)))
            y = float(field.crack_y + radius * math.sin(float(angle)))
            value = field.evaluate(x, y)
            radius_values.append(float(radius))
            angle_values.append(float(angle))
            stress_values.append(value.stress_even + value.stress_odd)
    return field, LatticeStressSamples(
        radius=np.asarray(radius_values),
        theta=np.asarray(angle_values),
        stress=np.asarray(stress_values),
    )


def continuum_basis(samples: LatticeStressSamples, moduli: OddModuli) -> Array:
    """Return [n_points,4 components,8 coefficients] design values."""

    n_points = len(samples.radius)
    design = np.zeros((n_points, 4, 8), dtype=float)
    unique_radii = np.unique(samples.radius)
    for radius in unique_radii:
        ids = np.flatnonzero(np.isclose(samples.radius, radius, atol=1.0e-12))
        theta = samples.theta[ids]
        fields = (
            sample_K_field(1.0, 0.0, moduli, theta, 0.5)["sigma"] * radius ** -0.5,
            sample_K_field(0.0, 1.0, moduli, theta, 0.5)["sigma"] * radius ** -0.5,
            sample_K_field(1.0, 0.0, moduli, theta, 1.5)["sigma"] * radius ** 0.5,
            sample_K_field(0.0, 1.0, moduli, theta, 1.5)["sigma"] * radius ** 0.5,
        )
        for local_index, point_id in enumerate(ids):
            for component, (row, column) in enumerate(COMPONENTS):
                for basis_id, basis_field in enumerate(fields):
                    design[point_id, component, basis_id] = basis_field[
                        local_index, row, column
                    ]
                design[point_id, component, 4 + component] = 1.0
    return design


def fit_stress_basis(
    samples: LatticeStressSamples,
    design: Array,
    r_inner: float,
    r_outer: float,
) -> tuple[Array, float, Array, float, Array]:
    point_mask = (samples.radius >= r_inner - 1.0e-12) & (
        samples.radius <= r_outer + 1.0e-12
    )
    selected_design = design[point_mask].reshape((-1, design.shape[-1]))
    selected_stress = samples.stress[point_mask].reshape(-1)
    coefficients, *_ = np.linalg.lstsq(selected_design, selected_stress, rcond=None)
    prediction = selected_design @ coefficients
    denominator = max(float(np.linalg.norm(selected_stress)), 1.0e-30)
    relative_residual = float(np.linalg.norm(selected_stress - prediction) / denominator)

    leading_design = selected_design[:, :2]
    leading_coefficients, *_ = np.linalg.lstsq(
        leading_design, selected_stress, rcond=None
    )
    leading_prediction = leading_design @ leading_coefficients
    leading_relative_residual = float(
        np.linalg.norm(selected_stress - leading_prediction) / denominator
    )
    return (
        coefficients,
        relative_residual,
        leading_coefficients,
        leading_relative_residual,
        point_mask,
    )


def row_from_fit(
    *,
    global_k_o: float,
    tip: str,
    local_k_o: float,
    basis_name: str,
    basis_local_k_o: float,
    r_inner: float,
    r_outer: float,
    coefficients: Array,
    relative_residual: float,
    leading_coefficients: Array,
    leading_relative_residual: float,
    n_points: int,
) -> dict[str, object]:
    return {
        "global_k_o": global_k_o,
        "tip": tip,
        "local_k_o": local_k_o,
        "basis": basis_name,
        "basis_local_k_o": basis_local_k_o,
        "r_inner": r_inner,
        "r_outer": r_outer,
        "n_spatial_points": n_points,
        "K_I": float(coefficients[0]),
        "K_II": float(coefficients[1]),
        "C_I_lambda_3_over_2": float(coefficients[2]),
        "C_II_lambda_3_over_2": float(coefficients[3]),
        "background_sigma_xx": float(coefficients[4]),
        "background_sigma_xy": float(coefficients[5]),
        "background_sigma_yx": float(coefficients[6]),
        "background_sigma_yy": float(coefficients[7]),
        "relative_L2_residual": relative_residual,
        "leading_only_K_I": float(leading_coefficients[0]),
        "leading_only_K_II": float(leading_coefficients[1]),
        "leading_only_relative_L2_residual": leading_relative_residual,
    }


def analyze_case(
    *,
    nx: int,
    ny: int,
    crack_half_length: float,
    k_o: float,
    tip: str,
    radii: Array,
    angles: Array,
    fit_radius: float,
    annuli: tuple[tuple[float, float], ...],
) -> tuple[list[dict[str, object]], dict[str, object], LatticeStressSamples, Array]:
    model = ActiveCrackedStrip(
        nx=nx,
        ny=ny,
        crack_half_length=crack_half_length,
        k=1.0,
        k_o=k_o,
    )
    displacement, _reactions, equilibrium_residual = model.solve(delta=1.0)
    field, samples = sample_lattice_stress(
        model, displacement, tip, radii, angles, fit_radius
    )
    matched_moduli = homogenized_moduli(model.k, field.k_o_local)
    passive_moduli = homogenized_moduli(model.k, 0.0)
    matched_design = continuum_basis(samples, matched_moduli)
    passive_design = continuum_basis(samples, passive_moduli)

    rows: list[dict[str, object]] = []
    for r_inner, r_outer in annuli:
        for basis_name, basis_local_k_o, design in (
            ("matched_odd", field.k_o_local, matched_design),
            ("passive", 0.0, passive_design),
        ):
            coefficients, residual, leading, leading_residual, mask = fit_stress_basis(
                samples, design, r_inner, r_outer
            )
            rows.append(
                row_from_fit(
                    global_k_o=k_o,
                    tip=tip,
                    local_k_o=field.k_o_local,
                    basis_name=basis_name,
                    basis_local_k_o=basis_local_k_o,
                    r_inner=r_inner,
                    r_outer=r_outer,
                    coefficients=coefficients,
                    relative_residual=residual,
                    leading_coefficients=leading,
                    leading_relative_residual=leading_residual,
                    n_points=int(np.count_nonzero(mask)),
                )
            )

    metadata = {
        "global_k_o": k_o,
        "tip": tip,
        "local_k_o": field.k_o_local,
        "equilibrium_residual_inf": equilibrium_residual,
        "tip_x_global": field.tip_x_global,
        "crack_y": field.crack_y,
    }
    return rows, metadata, samples, matched_design


def run_analysis(output_dir: Path) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    nx, ny, crack_half_length = 80, 56, 10.0
    fit_radius = 4.2
    radii = np.arange(3.5, 10.0 + 1.0e-12, 0.5)
    angles = np.linspace(-math.pi + 0.08, math.pi - 0.08, 97)
    annuli = ((3.5, 7.0), (4.0, 8.0), (5.0, 9.0), (6.0, 10.0))
    nominal_annulus = (3.5, 7.0)

    all_rows: list[dict[str, object]] = []
    metadata_rows: list[dict[str, object]] = []
    cached_case: dict[tuple[float, str], tuple[LatticeStressSamples, Array]] = {}
    cases = (
        (0.0, "right"),
        (0.05, "right"),
        (0.10, "right"),
        (0.15, "right"),
        (0.20, "right"),
        (-0.10, "left"),
        (-0.15, "left"),
    )
    for k_o, tip in cases:
        rows, metadata, samples, design = analyze_case(
            nx=nx,
            ny=ny,
            crack_half_length=crack_half_length,
            k_o=k_o,
            tip=tip,
            radii=radii,
            angles=angles,
            fit_radius=fit_radius,
            annuli=annuli,
        )
        all_rows.extend(rows)
        metadata_rows.append(metadata)
        cached_case[(k_o, tip)] = (samples, design)

    write_csv(output_dir / "stress_fit_annulus_scan.csv", all_rows)
    write_csv(output_dir / "case_metadata.csv", metadata_rows)

    nominal_rows = [
        row
        for row in all_rows
        if abs(float(row["r_inner"]) - nominal_annulus[0]) < 1.0e-12
        and abs(float(row["r_outer"]) - nominal_annulus[1]) < 1.0e-12
    ]
    write_csv(output_dir / "matched_vs_passive_basis.csv", nominal_rows)

    mirror_rows: list[dict[str, object]] = []
    for magnitude in (0.10, 0.15):
        right = next(
            row
            for row in nominal_rows
            if row["basis"] == "matched_odd"
            and row["tip"] == "right"
            and abs(float(row["global_k_o"]) - magnitude) < 1.0e-12
        )
        left = next(
            row
            for row in nominal_rows
            if row["basis"] == "matched_odd"
            and row["tip"] == "left"
            and abs(float(row["global_k_o"]) + magnitude) < 1.0e-12
        )
        coefficient_names = (
            "K_I",
            "K_II",
            "C_I_lambda_3_over_2",
            "C_II_lambda_3_over_2",
            "background_sigma_xx",
            "background_sigma_xy",
            "background_sigma_yx",
            "background_sigma_yy",
        )
        differences = [abs(float(right[name]) - float(left[name])) for name in coefficient_names]
        mirror_rows.append(
            {
                "abs_k_o": magnitude,
                "max_abs_coefficient_difference": max(differences),
                "absolute_residual_difference": abs(
                    float(right["relative_L2_residual"])
                    - float(left["relative_L2_residual"])
                ),
            }
        )
    write_csv(output_dir / "mirror_symmetry_check.csv", mirror_rows)

    # Export one representative angular/radial comparison for plotting.
    representative_row = next(
        row
        for row in nominal_rows
        if row["basis"] == "matched_odd"
        and row["tip"] == "right"
        and abs(float(row["global_k_o"]) - 0.15) < 1.0e-12
    )
    representative_samples, representative_design = cached_case[(0.15, "right")]
    coefficient_vector = np.array(
        [
            representative_row["K_I"],
            representative_row["K_II"],
            representative_row["C_I_lambda_3_over_2"],
            representative_row["C_II_lambda_3_over_2"],
            representative_row["background_sigma_xx"],
            representative_row["background_sigma_xy"],
            representative_row["background_sigma_yx"],
            representative_row["background_sigma_yy"],
        ],
        dtype=float,
    )
    predicted = np.einsum("pck,k->pc", representative_design, coefficient_vector)
    comparison_rows: list[dict[str, object]] = []
    for point_id in range(len(representative_samples.radius)):
        if not (
            nominal_annulus[0] - 1.0e-12
            <= representative_samples.radius[point_id]
            <= nominal_annulus[1] + 1.0e-12
        ):
            continue
        row: dict[str, object] = {
            "radius": float(representative_samples.radius[point_id]),
            "theta": float(representative_samples.theta[point_id]),
        }
        for component, name in enumerate(("xx", "xy", "yx", "yy")):
            row[f"lattice_sigma_{name}"] = float(
                representative_samples.stress[point_id].reshape(-1)[component]
            )
            row[f"fit_sigma_{name}"] = float(predicted[point_id, component])
        comparison_rows.append(row)
    write_csv(output_dir / "representative_field_comparison.csv", comparison_rows)

    matched_nominal = [row for row in nominal_rows if row["basis"] == "matched_odd"]
    basis_comparison = []
    for row in matched_nominal:
        if float(row["global_k_o"]) <= 0.0 or row["tip"] != "right":
            continue
        passive = next(
            candidate
            for candidate in nominal_rows
            if candidate["basis"] == "passive"
            and candidate["tip"] == row["tip"]
            and abs(float(candidate["global_k_o"]) - float(row["global_k_o"])) < 1.0e-12
        )
        basis_comparison.append(
            {
                "k_o": float(row["global_k_o"]),
                "matched_residual": float(row["relative_L2_residual"]),
                "passive_basis_residual": float(passive["relative_L2_residual"]),
                "relative_residual_reduction": 1.0
                - float(row["relative_L2_residual"])
                / float(passive["relative_L2_residual"]),
            }
        )
    write_csv(output_dir / "odd_basis_improvement.csv", basis_comparison)

    passive_row = next(
        row
        for row in matched_nominal
        if abs(float(row["global_k_o"])) < 1.0e-12 and row["tip"] == "right"
    )
    representative_improvement = next(
        row for row in basis_comparison if abs(float(row["k_o"]) - 0.15) < 1.0e-12
    )
    annulus_KI = np.array(
        [
            float(row["K_I"])
            for row in all_rows
            if row["basis"] == "matched_odd"
            and row["tip"] == "right"
            and abs(float(row["global_k_o"]) - 0.15) < 1.0e-12
        ]
    )
    summary: dict[str, object] = {
        "grid_nx": nx,
        "grid_ny": ny,
        "crack_half_length": crack_half_length,
        "mls_fit_radius": fit_radius,
        "nominal_annulus": list(nominal_annulus),
        "fit_model": "lambda=1/2 + lambda=3/2 + constant stress",
        "passive_nominal_relative_residual": float(passive_row["relative_L2_residual"]),
        "passive_nominal_abs_KII_over_KI": abs(float(passive_row["K_II"]))
        / abs(float(passive_row["K_I"])),
        "ko_0p15_matched_relative_residual": float(
            representative_improvement["matched_residual"]
        ),
        "ko_0p15_passive_basis_relative_residual": float(
            representative_improvement["passive_basis_residual"]
        ),
        "ko_0p15_relative_residual_reduction": float(
            representative_improvement["relative_residual_reduction"]
        ),
        "ko_0p15_KI_annulus_coefficient_of_variation": float(
            np.std(annulus_KI, ddof=1) / np.mean(annulus_KI)
        ),
        "mirror_max_abs_coefficient_difference": max(
            float(row["max_abs_coefficient_difference"]) for row in mirror_rows
        ),
        "mirror_max_abs_residual_difference": max(
            float(row["absolute_residual_difference"]) for row in mirror_rows
        ),
        "max_equilibrium_residual_inf": max(
            float(row["equilibrium_residual_inf"]) for row in metadata_rows
        ),
        "pass": bool(
            float(passive_row["relative_L2_residual"]) < 0.12
            and abs(float(passive_row["K_II"]) / float(passive_row["K_I"])) < 0.02
            and float(representative_improvement["matched_residual"]) < 0.12
            and float(representative_improvement["relative_residual_reduction"]) > 0.20
            and max(float(row["max_abs_coefficient_difference"]) for row in mirror_rows)
            < 1.0e-11
        ),
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary
